version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    env_file: ./.env
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_PORT
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
